export interface SeedItem {
  id: string;
  title: string;
  url: string;
  description: string;
  image_url: string;
  category: string;
  email: string;
  status: string;
  created_at: string;
  detailed_overview?: string;
  key_features?: string[];
  key_features_descriptions?: string[];
  rating?: number;
  rating_count?: number;
  customer_review?: string;
  customer_review_author?: string;
  customer_review_2?: string;
  customer_review_2_author?: string;
  integration_guide_1_label?: string;
  integration_guide_1_url?: string;
  integration_guide_2_label?: string;
  integration_guide_2_url?: string;
}

export const SEED_ITEMS: SeedItem[] = [
  // ==================== 1. Visual & Design (5 items) ====================
  {
    id: "seed-pebblely",
    title: "Pebblely",
    url: "https://pebblely.com",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548671/jzgs3z9s9m1rt1zjiq8t.png",
    description: "Beautiful AI product photography in seconds. Turn any boring product photo into a professional studio shot.",
    category: "Visual & Design",
    email: "creator@pebblely.com",
    status: "approved",
    created_at: "2026-05-23T12:00:00Z",
    detailed_overview: "Pebblely utilizes generative AI to transform basic product images into stunning marketing assets. By automatically removing backgrounds and generating realistic studio scenes, it eliminates the need for expensive photoshoots, saving solo creators hours of tedious manual editing.",
    key_features: ["AI Scene Generation", "Instant Background Removal", "Multi-Asset Batch Export"],
    key_features_descriptions: [
      "Instantly place your product in dozens of realistic, AI-generated lifestyle environments and seasonal themes.",
      "Flawlessly extract your product from any background with surgical-grade precision in one click.",
      "Generate and download multiple product variants and sizes optimized for different social channels simultaneously."
    ],
    rating: 4.8,
    rating_count: 340,
    customer_review: "Saved us over 40 hours of manual editing last month alone. Absolute game-changer for solo sellers!",
    customer_review_author: "Sarah J. - Shopify Plus Merchant",
    customer_review_2: "The AI-generated scenes look indistinguishable from real photos. It allowed us to launch a whole new catalog in days rather than months.",
    customer_review_2_author: "James T. - D2C Fashion Founder",
    integration_guide_1_label: "Pebblely Shopify App Store",
    integration_guide_1_url: "https://apps.shopify.com/pebblely",
    integration_guide_2_label: "Official Pebblely Portal",
    integration_guide_2_url: "https://pebblely.com"
  },
  {
    id: "seed-flair-ai",
    title: "Flair AI",
    url: "https://flair.ai",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548672/hfb0e3nybqrtks1wq7qc.png",
    description: "The AI design tool for branded content. Generate high-end product assets and campaigns instantly.",
    category: "Visual & Design",
    email: "creator@flair.ai",
    status: "approved",
    created_at: "2026-05-23T11:50:00Z",
    detailed_overview: "Flair AI is a drag-and-drop design tool engineered specifically for consumer brands. It allows users to place their products in high-conversion digital environments, complete with smart lighting and contextual props that reflect premium brand aesthetics.",
    key_features: ["Smart Lighting Placement", "Drag-and-Drop Props", "High-Res Content Upscaling"],
    key_features_descriptions: [
      "Simulate natural environment lighting and shadow tracking to match your product perfectly with the generated background.",
      "Browse an extensive digital catalog of props, platforms, and botanical elements to construct a custom scene.",
      "Render your final marketing assets in ultra-high definition suitable for physical print and digital banner displays."
    ],
    rating: 4.7,
    rating_count: 195,
    customer_review: "The absolute fastest way to create high-end product ads without a professional studio crew.",
    customer_review_author: "David K. - Brand Director",
    customer_review_2: "It's like having a creative agency in your pocket. The shadow casting and lighting matching is incredibly realistic.",
    customer_review_2_author: "Sophia M. - Cosmetics Brand Owner",
    integration_guide_1_label: "Official Flair AI Portal",
    integration_guide_1_url: "https://flair.ai",
    integration_guide_2_label: "Flair AI Design Workspace",
    integration_guide_2_url: "https://flair.ai"
  },
  {
    id: "seed-pixelcut",
    title: "Pixelcut",
    url: "https://www.pixelcut.ai",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548673/znri2hnkkvneeqsicctp.png",
    description: "Fast and clean background removal and product photo editing tailored for online commerce.",
    category: "Visual & Design",
    email: "creator@pixelcut.ai",
    status: "approved",
    created_at: "2026-05-23T11:40:00Z",
    detailed_overview: "Pixelcut focuses on lightning-fast mobile and web editing for active e-commerce merchants. Its optimized AI model handles bulk background cutouts instantly, making it the perfect tool for multi-channel sellers listing hundreds of items daily.",
    key_features: ["Bulk Object Eraser", "Shadow Control Customization", "E-commerce Template Library"],
    key_features_descriptions: [
      "Select and remove multiple background components or unwanted elements in batch mode within seconds.",
      "Dynamically adjust the blur, angle, and opacity of 3D shadows to ground your product realistically.",
      "Access hundreds of pre-sized canvas layouts optimized for Amazon, Etsy, eBay, and Instagram storefronts."
    ],
    rating: 4.9,
    rating_count: 512,
    customer_review: "Listing new items on Etsy used to take all day. Now with Pixelcut, it's done in minutes.",
    customer_review_author: "Emma L. - Boutique Owner",
    customer_review_2: "Bulk background removal is a lifesaver. We cut out hundreds of product shots in one go and they look flawless.",
    customer_review_2_author: "Daniel C. - eBay Power Seller",
    integration_guide_1_label: "Pixelcut Web Portal",
    integration_guide_1_url: "https://www.pixelcut.ai",
    integration_guide_2_label: "Pixelcut Professional Templates",
    integration_guide_2_url: "https://www.pixelcut.ai/templates"
  },
  {
    id: "seed-claid-ai",
    title: "Claid.ai",
    url: "https://claid.ai",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548674/mpgsuhx4hhttt9qyi3bm.png",
    description: "AI-powered image upscaler and editor built to enhance user-generated marketplace photos.",
    category: "Visual & Design",
    email: "creator@claid.ai",
    status: "approved",
    created_at: "2026-05-23T11:30:00Z",
    detailed_overview: "Claid.ai specializes in fixing poor quality product photos automatically. It uses sophisticated neural networks to sharpen blurry textures, fix complex lighting issues, and standardize pixel dimensions for strict multi-vendor marketplaces.",
    key_features: ["Automated Image Enhancement", "Marketplace Photo Standardizer", "Smart Light Correction"],
    key_features_descriptions: [
      "Upscale user-generated or low-resolution product photos up to 4x while restoring original details and textures.",
      "Standardize dimensions, white balance, paddings, and alignment to comply with Amazon and Google Shopping guidelines.",
      "Re-light products automatically to fix dark supplier images and establish cohesive catalog branding."
    ],
    rating: 4.6,
    rating_count: 128,
    customer_review: "Drastically improved our catalog quality. Conversions went up after cleaning up supplier images.",
    customer_review_author: "Marcus T. - Dropshipping Manager",
    customer_review_2: "The automated image enhancement is highly effective. It standardizes thousands of low-res images from suppliers into high-res shots.",
    customer_review_2_author: "Oliver R. - Multi-channel Retailer",
    integration_guide_1_label: "Claid.ai Developer Documentation",
    integration_guide_1_url: "https://docs.claid.ai/",
    integration_guide_2_label: "Claid.ai Official Portal",
    integration_guide_2_url: "https://claid.ai"
  },
  {
    id: "seed-photoroom",
    title: "Photoroom",
    url: "https://www.photoroom.com",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548675/riypk4qrjhbswnlz24x5.png",
    description: "The all-in-one creative photo editing platform that helps small business owners create pro product images.",
    category: "Visual & Design",
    email: "creator@photoroom.com",
    status: "approved",
    created_at: "2026-05-23T11:20:00Z",
    detailed_overview: "Photoroom is a powerhouse for mobile commerce sellers. It enables swift, pro-level retouching directly from a smartphone or browser, allowing sellers to clean up product listings, add stylized text, and format pictures for marketplaces seamlessly.",
    key_features: ["Pro Retouching Suite", "Batch Processing Engine", "Dynamic Text Overlay AI"],
    key_features_descriptions: [
      "Use precise, machine-learning based brush tools to instantly wipe out blemishes, dust, or unwanted shadows.",
      "Edit thousands of images simultaneously to establish uniform sizing, margins, and background palettes.",
      "Generate catchy, context-aware brand captions and price tag designs dynamically on top of your visuals."
    ],
    rating: 4.8,
    rating_count: 890,
    customer_review: "Our team uses this every single day. The mobile app parity with web is incredible.",
    customer_review_author: "Jessica H. - Content Lead",
    customer_review_2: "Photoroom has become an essential part of our workflow. The mobile-to-web sync is seamless, and background removal is the best on the market.",
    customer_review_2_author: "Lucas P. - Reseller",
    integration_guide_1_label: "Photoroom Developer Portal",
    integration_guide_1_url: "https://www.photoroom.com/api/",
    integration_guide_2_label: "Photoroom Official Portal",
    integration_guide_2_url: "https://www.photoroom.com"
  },

  // ==================== 2. Copywriting & Marketing (5 items) ====================
  {
    id: "seed-predis-ai",
    title: "Predis.ai",
    url: "https://predis.ai",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548676/gfxtwxiwzpr5bjryh3hi.png",
    description: "AI social media post generator. Create video reels, carousels, and captions just from a text prompt.",
    category: "Copywriting & Marketing",
    email: "creator@predis.ai",
    status: "approved",
    created_at: "2026-05-23T11:10:00Z",
    detailed_overview: "Predis.ai bridges the gap between product catalogs and social media. By simply inputting a product URL or text description, the AI spits out fully edited Instagram reels, interactive carousels, and engaging captions optimized for store traffic.",
    key_features: ["AI Video Reels Generator", "Competitor Analysis Dashboard", "Direct Meta Scheduling"],
    key_features_descriptions: [
      "Convert catalog listings into beautiful, animated social media video clips complete with royalty-free audio tracks.",
      "Track and analyze your competitors' high-engagement posts to dynamically model your content framework.",
      "Schedule, publish, and track analytics on Meta, TikTok, Pinterest, and LinkedIn directly from the Predis interface."
    ],
    rating: 4.7,
    rating_count: 210,
    customer_review: "Managing social accounts for three brands became manageable thanks to Predis.",
    customer_review_author: "Alex B. - Multi-Store Owner",
    customer_review_2: "It automatically reads our Shopify product page and spits out a complete Instagram video reel. Absolute game changer!",
    customer_review_2_author: "Mia S. - Social Commerce Specialist",
    integration_guide_1_label: "Predis.ai Shopify App Store",
    integration_guide_1_url: "https://apps.shopify.com/predis-ai",
    integration_guide_2_label: "Official Predis.ai Portal",
    integration_guide_2_url: "https://predis.ai"
  },
  {
    id: "seed-jasper",
    title: "Jasper",
    url: "https://www.jasper.ai",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548677/kkik6unnl2ij4lst3xwj.png",
    description: "Enterprise AI copywriter optimized to write high-converting Shopify product descriptions and ads.",
    category: "Copywriting & Marketing",
    email: "creator@jasper.ai",
    status: "approved",
    created_at: "2026-05-23T11:00:00Z",
    detailed_overview: "Jasper is an advanced writing assistant trained extensively on conversion psychology. It helps merchants brainstorm catchy hooks, craft SEO-friendly product pages, and generate high-performing ad variants tailored to target audience segments.",
    key_features: ["Brand Voice Personalization", "SEO Keywords Injector", "A/B Test Ad Variant Writer"],
    key_features_descriptions: [
      "Upload existing product copy to train the AI model on your brand's unique tone, vocabulary, and style guidelines.",
      "Seamlessly inject high-value SEO search queries into descriptions without disrupting readable sentence structures.",
      "Instantly generate 5+ variations of promotional copy optimized for Facebook, Google, and Pinterest campaigns."
    ],
    rating: 4.8,
    rating_count: 940,
    customer_review: "Our ad copy CTR increased by 25% since we let Jasper write our product taglines.",
    customer_review_author: "Ryan M. - Growth Marketer",
    customer_review_2: "We use Jasper to write all our Facebook ad copy variants and Shopify SEO descriptions. The conversion increase is very real.",
    customer_review_2_author: "Nathan G. - E-commerce Growth Lead",
    integration_guide_1_label: "Jasper Shopify App Store",
    integration_guide_1_url: "https://apps.shopify.com/jasper-ai",
    integration_guide_2_label: "Official Jasper AI Portal",
    integration_guide_2_url: "https://www.jasper.ai"
  },
  {
    id: "seed-copy-ai",
    title: "Copy.ai",
    url: "https://www.copy.ai",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548678/nazgsdvnaaderl105ydz.png",
    description: "AI marketing OS designed to automate bulk e-commerce email marketing campaigns and ad copies.",
    category: "Copywriting & Marketing",
    email: "creator@copy.ai",
    status: "approved",
    created_at: "2026-05-23T10:50:00Z",
    detailed_overview: "Copy.ai focuses on large-scale marketing workflows. Instead of writing individual newsletters, its e-commerce automation operating system allows sellers to instantly generate entire email sequencing flows based on consumer behavior triggers.",
    key_features: ["Marketing Workflow Automation", "Bulk Email Copy Sequencer", "Multi-Language Ad Translator"],
    key_features_descriptions: [
      "Establish automated workflows that write custom welcome emails and abandoned cart triggers instantly.",
      "Draft cohesive product email chains covering product launches, educational series, and discount campaigns.",
      "Translate highly localized ad copy into over 25+ languages, adhering strictly to global marketing idioms."
    ],
    rating: 4.7,
    rating_count: 670,
    customer_review: "Automating our abandoned cart email sequences took less than 10 minutes with Copy.ai.",
    customer_review_author: "Liam F. - Operations Lead",
    customer_review_2: "Automating email marketing workflows with Copy.ai is super easy. It writes high-converting abandoned cart sequences in minutes.",
    customer_review_2_author: "Ella J. - CRM Manager",
    integration_guide_1_label: "Copy.ai Official Portal",
    integration_guide_1_url: "https://www.copy.ai",
    integration_guide_2_label: "Copy.ai Workspace Login",
    integration_guide_2_url: "https://www.copy.ai"
  },
  {
    id: "seed-adcreative-ai",
    title: "AdCreative.ai",
    url: "https://www.adcreative.ai",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548679/kfiduth1jljkqicg7eqo.png",
    description: "Generate conversion-focused ad creatives and banners within seconds using a highly trained prediction AI.",
    category: "Copywriting & Marketing",
    email: "creator@adcreative.ai",
    status: "approved",
    created_at: "2026-05-23T10:40:00Z",
    detailed_overview: "AdCreative.ai is a data-backed creative engine. It analyzes millions of successful advertising banners across the web to automatically generate layouts that drive users to click, minimizing ad spend fatigue.",
    key_features: ["Conversion Rate Prediction AI", "Bulk Banner Ad Resizer", "Brand Kit Auto-Integration"],
    key_features_descriptions: [
      "Submit draft designs and receive an instant scoring evaluation forecasting the likely CTR (Click-Through Rate).",
      "Generate a single layout and export it in 15+ aspect dimensions suited for Meta, Google, and TikTok banner placements.",
      "Upload brand colors, logos, and custom typographies to ensure all AI designs align with company assets."
    ],
    rating: 4.6,
    rating_count: 325,
    customer_review: "Takes the guesswork out of creative testing. The AI-recommended layouts just perform better.",
    customer_review_author: "Chloe W. - Paid Media Specialist",
    customer_review_2: "The AI generated banner variants perform significantly better in A/B testing than our manual drafts. Incredible ROI.",
    customer_review_2_author: "Ethan L. - Paid Ads Specialist",
    integration_guide_1_label: "AdCreative.ai Official Portal",
    integration_guide_1_url: "https://www.adcreative.ai",
    integration_guide_2_label: "AdCreative.ai Quickstart Guide",
    integration_guide_2_url: "https://www.adcreative.ai"
  },
  {
    id: "seed-glossai",
    title: "GlossAi",
    url: "https://gloss.ai",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548680/pdxs4htgbku4wkfyrc5l.png",
    description: "Turn long-form customer review videos or podcasts into bite-sized, viral social media shorts for your brand.",
    category: "Copywriting & Marketing",
    email: "creator@gloss.ai",
    status: "approved",
    created_at: "2026-05-23T10:30:00Z",
    detailed_overview: "GlossAi repurposes video content to unlock social proof potential. It scans long unboxing videos, customer reviews, or brand podcasts to isolate the most exciting segments, auto-generating short-form video clips complete with stylish subtitles.",
    key_features: ["AI Video Summarization", "Auto-Subtitling Engine", "Social Media Trend Matcher"],
    key_features_descriptions: [
      "Detect dynamic peaks in long videos, automatically slicing the best unboxing reviews and reactions into clips.",
      "Instantly overlay highly legible, interactive subtitles styled after successful content creators' frameworks.",
      "Analyze trending TikTok and Instagram audio formats to match the speed and tone of your generated shorts."
    ],
    rating: 4.5,
    rating_count: 88,
    customer_review: "We generated a month's worth of TikTok shorts from just one single YouTube review.",
    customer_review_author: "Tyler V. - Video Producer",
    customer_review_2: "It isolates our best video reviews and auto-formats them for TikTok with styling. Incredible time saver for organic marketing.",
    customer_review_2_author: "Zoe B. - Brand Storyteller",
    integration_guide_1_label: "GlossAi Official Portal",
    integration_guide_1_url: "https://gloss.ai",
    integration_guide_2_label: "GlossAi Workspace Login",
    integration_guide_2_url: "https://gloss.ai"
  },

  // ==================== 3. Store Optimization (5 items) ====================
  {
    id: "seed-omnisearch-ai",
    title: "OmniSearch",
    url: "https://omnisearch.ai",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548680/unpar5gnflwcgsmn4ems.png",
    description: "Lightning-fast semantic search for large-scale e-commerce product catalogs.",
    category: "Store Optimization",
    email: "creator@omnisearch.ai",
    status: "approved",
    created_at: "2026-05-23T10:20:00Z",
    detailed_overview: "OmniSearch is a powerful search engine designed to scan and index complex catalog attributes, including text, PDFs, audio, and product files, allowing store owners to offer Google-like search queries that match buyer intent accurately.",
    key_features: ["Instant Semantic Search", "Audio & Video Transcription Search", "Multi-file Format Indexer"],
    key_features_descriptions: [
      "Understand the contextual meaning of search phrases rather than relying solely on rigid product tag matches.",
      "Search inside product explainer videos, podcasts, or tutorials to serve relevant files to e-commerce buyers.",
      "Instantly parse and index instruction manuals, PDFs, warranties, and bulk specs associated with product pages."
    ],
    rating: 4.8,
    rating_count: 145,
    customer_review: "Unlocked search visibility for our complex 5,000 SKU clothing store catalog overnight.",
    customer_review_author: "Sarah J. - Shopify Plus Merchant",
    customer_review_2: "The semantic search is incredibly smart. It understands user search intent and delivers highly accurate results instantly.",
    customer_review_2_author: "Marcus K. - CTO",
    integration_guide_1_label: "OmniSearch Official Portal",
    integration_guide_1_url: "https://omnisearch.ai",
    integration_guide_2_label: "OmniSearch Support Portal",
    integration_guide_2_url: "https://omnisearch.ai"
  },
  {
    id: "seed-instant",
    title: "Instant",
    url: "https://www.instant.so",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548681/kujvcvsmnttnknrdwqww.png",
    description: "The fastest Shopify landing page builder with pre-made, high-converting drag-and-drop elements.",
    category: "Store Optimization",
    email: "creator@instant.so",
    status: "approved",
    created_at: "2026-05-23T10:10:00Z",
    detailed_overview: "Instant lets brand owners launch optimized promotional landing pages without touching code. Its server-side rendering architecture ensures pages load instantly, minimizing bounce rates and maximizing dynamic checkout conversions.",
    key_features: ["No-Code Page Structurer", "Ultra-Fast Page Load Speed", "Shopify Section Exporter"],
    key_features_descriptions: [
      "Construct high-end landing pages in a robust visual interface using validated conversion layouts.",
      "Publish pages that achieve 95+ Google Lighthouse scores through optimized JS and compressed media pipelines.",
      "Export custom landing page components directly as native, editable Shopify Theme Sections."
    ],
    rating: 4.9,
    rating_count: 420,
    customer_review: "The load speeds on our landing pages dropped below 0.5s. Our conversion rates spiked.",
    customer_review_author: "Nate D. - Direct-to-Consumer Founder",
    customer_review_2: "Building Shopify landers is super fast with Instant. Elements are pre-optimized for speed and mobile viewports.",
    customer_review_2_author: "William H. - Conversion Specialist",
    integration_guide_1_label: "Instant Shopify App Store",
    integration_guide_1_url: "https://apps.shopify.com/instant-brand-page-builder",
    integration_guide_2_label: "Instant Official Help Center",
    integration_guide_2_url: "https://help.instant.so/"
  },
  {
    id: "seed-alia-popups",
    title: "Alia Popups",
    url: "https://www.aliapopups.com",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548682/elxbajfhpn8zsn7nvpct.png",
    description: "Smart behavioral popups that prevent shopping cart abandonment with dynamic, real-time incentives.",
    category: "Store Optimization",
    email: "creator@aliapopups.com",
    status: "approved",
    created_at: "2026-05-23T10:00:00Z",
    detailed_overview: "Alia Popups uses smart exit-intent tracking to rescue lost revenue. The platform accurately senses when a customer is about to leave your storefront and deploys targeted, personalized offers to secure the checkout session.",
    key_features: ["Exit-Intent Smart Detection", "Dynamic Coupon Code Generator", "A/B Split Testing Panel"],
    key_features_descriptions: [
      "Trigger incentive popups precisely when the user's cursor tracks toward the tab close or back button.",
      "Inject unique, limited-lifetime coupon codes directly into Shopify checkout to incentivize instant buying.",
      "Test different discount percentages, banner layouts, and trigger delays to optimize checkout recovery."
    ],
    rating: 4.7,
    rating_count: 156,
    customer_review: "Recovered over $5,000 in sales during our first week of launching Alia.",
    customer_review_author: "Sophia R. - E-commerce Director",
    customer_review_2: "The exit-intent coupon popup rescued hundreds of checkouts that were about to abandon their shopping carts.",
    customer_review_2_author: "Olivia P. - Store Operator",
    integration_guide_1_label: "Alia Popups Official Portal",
    integration_guide_1_url: "https://www.aliapopups.com",
    integration_guide_2_label: "Alia Quickstart Guide",
    integration_guide_2_url: "https://www.aliapopups.com"
  },
  {
    id: "seed-octane-ai",
    title: "Octane AI",
    url: "https://www.octaneai.com",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548683/cd2bptjgxefd0zz2xiwg.png",
    description: "Create engaging product recommendation quizzes to boost store sales and collect zero-party customer data.",
    category: "Store Optimization",
    email: "creator@octaneai.com",
    status: "approved",
    created_at: "2026-05-23T09:50:00Z",
    detailed_overview: "Octane AI enables personalized shopping journeys through guided quizzes. By questioning buyers about their exact preferences, it creates customized product recommendation sets that build trust and lift average order values.",
    key_features: ["Interactive Quiz Builder", "Zero-Party Data Collector", "Personalized Recommendation Engine"],
    key_features_descriptions: [
      "Design branching visual quizzes that capture buyer skin types, size preferences, or style desires.",
      "Build profiles for each customer to enrich your Klaviyo and Klaviyo email segments.",
      "Instantly map quiz answers to specific catalog products, generating a curated shopping cart."
    ],
    rating: 4.8,
    rating_count: 310,
    customer_review: "Our quiz is our highest-converting page. Customers love the tailored skincare advice.",
    customer_review_author: "Hannah P. - Wellness Brand Founder",
    customer_review_2: "The guided recommendation quiz has become our top converting funnel. Customers love the tailored, personal recommendations.",
    customer_review_2_author: "Grace V. - Skincare Brand Founder",
    integration_guide_1_label: "Octane AI Shopify App Store",
    integration_guide_1_url: "https://apps.shopify.com/octane-ai-quiz",
    integration_guide_2_label: "Octane AI Help Center",
    integration_guide_2_url: "https://help.octaneai.com/hc/en-us"
  },
  {
    id: "seed-loox",
    title: "Loox",
    url: "https://loox.app",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548684/dpaczrqxbrfulcqxm5po.png",
    description: "Beautiful photo and video product reviews app designed to build high trust and social proof.",
    category: "Store Optimization",
    email: "creator@loox.app",
    status: "approved",
    created_at: "2026-05-23T09:40:00Z",
    detailed_overview: "Loox automates the process of gathering customer validation. It sends beautiful, timed follow-up review request emails, encouraging buyers to upload photo and video proof in exchange for discounts, building premium social proof cards.",
    key_features: ["Automated Review Requester", "Photo/Video Gallery Widgets", "Review Incentives Manager"],
    key_features_descriptions: [
      "Send post-purchase emails at optimized delays to collect visual reviews and text ratings.",
      "Render gorgeous reviews carousels, masonry grids, and popup cards directly on product details pages.",
      "Offer unique discount codes to buyers who upload authentic product photos and video reviews."
    ],
    rating: 4.9,
    rating_count: 1420,
    customer_review: "Visual reviews are crucial for conversion. Loox makes collecting them entirely frictionless.",
    customer_review_author: "Ben S. - Gadget Store Owner",
    customer_review_2: "Timed review emails gather visual social proof automatically. Displaying customer photo reviews built immediate buyer trust.",
    customer_review_2_author: "Leo M. - E-commerce Manager",
    integration_guide_1_label: "Loox Shopify App Store",
    integration_guide_1_url: "https://apps.shopify.com/loox",
    integration_guide_2_label: "Loox Help Center Portal",
    integration_guide_2_url: "https://help.loox.io/"
  },

  // ==================== 4. Automation (5 items) ====================
  {
    id: "seed-tidio-lyro",
    title: "Tidio Lyro",
    url: "https://www.tidio.com/lyro/",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779842030/bzeogne5yc12gieqe7bw.png",
    description: "Conversational AI customer service chatbot that resolves up to 70% of customer inquiries on autopilot.",
    category: "Automation",
    email: "creator@tidio.com",
    status: "approved",
    created_at: "2026-05-23T09:30:00Z",
    detailed_overview: "Tidio Lyro handles customer care heavy lifting. Using state-of-the-art LLMs, it securely reads your store's FAQ data and answers order tracking or refund policy questions in seconds, reducing customer support queue times.",
    key_features: ["LLM-Powered Support Chatbot", "Order Tracking Live Sync", "Human Agent Handover Logic"],
    key_features_descriptions: [
      "Train the AI support agent in one click by feeding it your website URL, FAQs, or support articles.",
      "Connect Tidio with your shipping API to automatically inform customers of tracking numbers and delivery dates.",
      "Detect complex support queries automatically to route the chat session to a human representative."
    ],
    rating: 4.7,
    rating_count: 480,
    customer_review: "Lyro handles all our late-night support tickets perfectly without human intervention.",
    customer_review_author: "Oliver G. - Customer Success Lead",
    customer_review_2: "Lyro answers up to 70% of support tickets perfectly, and escalates complex queries to our human agents instantly.",
    customer_review_2_author: "Isabella C. - Operations Lead",
    integration_guide_1_label: "Tidio Shopify App Store",
    integration_guide_1_url: "https://apps.shopify.com/tidio-chat",
    integration_guide_2_label: "Tidio Help Center Portal",
    integration_guide_2_url: "https://help.tidio.com/"
  },
  {
    id: "seed-thoughtmetric",
    title: "ThoughtMetric",
    url: "https://thoughtmetric.io",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548686/sfmzuboc4zgwddksiznr.png",
    description: "E-commerce marketing attribution dashboard that tracks ROAS across TikTok, Meta, and Google Ads.",
    category: "Automation",
    email: "creator@thoughtmetric.io",
    status: "approved",
    created_at: "2026-05-23T09:20:00Z",
    detailed_overview: "ThoughtMetric solves pixel tracking inaccuracies caused by privacy updates. It utilizes advanced AI cookie-less tracking to trace the exact customer journey, assigning marketing attribution values to the channels that actually generated the sale.",
    key_features: ["Cookie-less Tracking Pixel", "Multi-Touch Attribution Model", "Cross-Channel Ad ROAS Dashboard"],
    key_features_descriptions: [
      "Track customer click behavior and store purchases securely without running into iOS tracking blocks.",
      "Compare first-click, last-click, and linear attribution paths to discover which campaign generated the lead.",
      "Centralize Meta, Google, and TikTok ad campaign metrics in one dashboard to track true overall ROAS."
    ],
    rating: 4.6,
    rating_count: 115,
    customer_review: "Finally, our Facebook and Shopify dashboard numbers match up. Lifesaver for ad tracking.",
    customer_review_author: "Kevin Z. - Digital Ads Manager",
    customer_review_2: "Allows us to trace back accurate ad conversions across multiple marketing channels. Solved our iOS 14 pixel tracking problems.",
    customer_review_2_author: "Jackson H. - Digital Marketing Director",
    integration_guide_1_label: "ThoughtMetric Shopify App Store",
    integration_guide_1_url: "https://apps.shopify.com/thoughtmetric",
    integration_guide_2_label: "ThoughtMetric Official Portal",
    integration_guide_2_url: "https://thoughtmetric.io"
  },
  {
    id: "seed-alloy-automation",
    title: "Alloy Automation",
    url: "https://runalloy.com",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548687/dije4pyucdqxeiohdazz.png",
    description: "No-code automation engine connecting your Shopify store, fulfillment warehouse, and marketing tools.",
    category: "Automation",
    email: "creator@runalloy.com",
    status: "approved",
    created_at: "2026-05-23T09:10:00Z",
    detailed_overview: "Alloy Automation functions as the central nervous system for complex store workflows. It enables non-technical operators to build logic chains, such as automatically tagging high-value customers or triggering warehouse shipping updates.",
    key_features: ["Visual Workflow Builder", "100+ Pre-built SaaS Triggers", "Advanced Logic & Tag Filter"],
    key_features_descriptions: [
      "Build complex, multi-app automated integrations using an intuitive visual drag-and-drop block builder.",
      "Unlock native API triggers connecting Shopify, Klaviyo, ShipStation, Gorgias, Slack, and Google Sheets.",
      "Establish logic conditions and loops to automate processes like tagging fraud orders or shipping notifications."
    ],
    rating: 4.8,
    rating_count: 260,
    customer_review: "Alloy automated our custom fraud prevention and loyalty program tagging completely.",
    customer_review_author: "Rachel E. - COO",
    customer_review_2: "Automating custom fraud screening and loyalty tagging flows across multiple apps is now zero-code and effortless.",
    customer_review_2_author: "Sophia S. - Chief Operations Officer",
    integration_guide_1_label: "Alloy Shopify App Store",
    integration_guide_1_url: "https://apps.shopify.com/alloy-automation",
    integration_guide_2_label: "Alloy Official Docs Portal",
    integration_guide_2_url: "https://docs.runalloy.com/"
  },
  {
    id: "seed-gorgias",
    title: "Gorgias",
    url: "https://www.gorgias.com",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548687/eocjie7aui3cvwphsxbn.png",
    description: "A specialized helpdesk for e-commerce merchants that centralizes customer support messages.",
    category: "Automation",
    email: "creator@gorgias.com",
    status: "approved",
    created_at: "2026-05-23T09:00:00Z",
    detailed_overview: "Gorgias pulls all communication channels into a single timeline. Whether a buyer messages via Instagram DM, email, or live chat, support teams can edit Shopify orders directly inside the ticket window without switching screens.",
    key_features: ["Multi-Channel Unified Inbox", "Direct Shopify Order Editor", "Macro Response Automation"],
    key_features_descriptions: [
      "Consolidate email, live chat, SMS, phone, Instagram, and Facebook conversations in one unified view.",
      "Cancel, refund, edit, or track Shopify order shipments directly inside the ticket details screen.",
      "Create smart pre-written templates that auto-fill order statuses and names to resolve tickets in one click."
    ],
    rating: 4.9,
    rating_count: 1140,
    customer_review: "Our first-response time dropped to under 5 minutes because everything is in one screen.",
    customer_review_author: "Daniel S. - Support Manager",
    customer_review_2: "Our agents can process refunds and edit Shopify orders directly inside customer support tickets. Massive time saver.",
    customer_review_2_author: "Mason T. - Customer Support Lead",
    integration_guide_1_label: "Gorgias Shopify App Store",
    integration_guide_1_url: "https://apps.shopify.com/gorgias",
    integration_guide_2_label: "Gorgias Help Center Portal",
    integration_guide_2_url: "https://help.gorgias.com/"
  },
  {
    id: "seed-matrixify",
    title: "Matrixify",
    url: "https://matrixify.app",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1779548688/rtuob3nxctgywqkecfa5.png",
    description: "Bulk data manager for Shopify. Easily import, export, and update thousands of products and orders.",
    category: "Automation",
    email: "creator@matrixify.app",
    status: "approved",
    created_at: "2026-05-23T08:50:00Z",
    detailed_overview: "Matrixify excels at heavy database data lifting. It allows store managers to export thousands of items into Excel or Google Sheets, perform mass price or inventory adjustments, and safely import everything back into Shopify with absolute data integrity.",
    key_features: ["Bulk Product Data Manager", "Metafield Excel Batch Editor", "Automated Backup Scheduler"],
    key_features_descriptions: [
      "Import, export, and update thousands of catalog products, customers, orders, or collections at once.",
      "Safely extract, edit, and mass-create Shopify custom metafields right inside Excel spreadsheets.",
      "Set up recurring scheduled automated catalog syncs connecting Matrixify with custom FTP/SFTP servers."
    ],
    rating: 4.9,
    rating_count: 620,
    customer_review: "Migrating 20,000 product variants from WooCommerce to Shopify took one click with Matrixify.",
    customer_review_author: "Andrew J. - E-commerce Consultant",
    customer_review_2: "Matrixify is the gold standard for bulk editing store catalog variants, metafields, and redirects in Google Sheets.",
    customer_review_2_author: "Luke D. - Shopify Architect",
    integration_guide_1_label: "Matrixify Shopify App Store",
    integration_guide_1_url: "https://apps.shopify.com/excel-export-import",
    integration_guide_2_label: "Matrixify Documentation Center",
    integration_guide_2_url: "https://matrixify.app/documentation/"
  },
  {
    id: "seed-sequenzy",
    title: "Sequenzy",
    url: "https://www.sequenzy.com",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1780655809/lieemtmwkxb1l7i5cqpb.gif",
    description: "The ultimate email platform for SaaS teams. Handles both marketing and transactional emails effortlessly.",
    category: "Automation",
    email: "team@getsequenzy.com",
    status: "approved",
    created_at: "2026-06-05T00:00:00Z",
    detailed_overview: JSON.stringify({
      overview: "Sequenzy is a developer-first email platform tailored perfectly for SaaS businesses. It seamlessly blends powerful marketing campaigns with robust transactional email delivery, eliminating the need to juggle multiple email providers. With its native MCP (Model Context Protocol) support, your AI agents can autonomously trigger onboarding flows, retention alerts, and promotional campaigns.",
      title1: "Unified Email Infrastructure",
      desc1: "Stop paying for both Mailchimp and Sendgrid. Sequenzy handles both marketing newsletters and crucial transactional password resets from one dashboard.",
      title2: "AI-Powered Automation",
      desc2: "With native MCP integration, your AI agents can autonomously design, schedule, and trigger complex behavioral email sequences without human intervention."
    }),
    key_features: ["Unified Marketing & Transactional Engine", "Native MCP Integration for AI", "Advanced Onboarding Flow Builder"],
    key_features_descriptions: [
      "Send beautiful newsletters and critical password reset emails from the exact same robust infrastructure.",
      "Empower your autonomous AI teams to draft, schedule, and trigger highly personalized emails using standard MCP protocols.",
      "Design complex behavioral email sequences to maximize user retention and product activation in the crucial first 14 days."
    ],
    rating: 5.0,
    rating_count: 89,
    customer_review: "The MCP integration is an absolute game-changer. Our AI agent now handles our entire onboarding email flow completely autonomously.",
    customer_review_author: "David M. - SaaS Founder",
    customer_review_2: "Finally, an email tool that doesn't charge Enterprise pricing for basic transactional workflows. Sequenzy replaced both Mailchimp and Sendgrid for us.",
    customer_review_2_author: "Elena R. - CTO",
    integration_guide_1_label: "Sequenzy MCP Features",
    integration_guide_1_url: "https://www.sequenzy.com/features/mcp",
    integration_guide_2_label: "MCP Setup Guide",
    integration_guide_2_url: "https://www.sequenzy.com/blog/mcp-setup-email-marketing-guide"
  }

  ,
  {
    id: "27e658a3-2e7d-4ba5-9ca8-9b640268dfda",
    title: "Klaviyo",
    url: "https://www.klaviyo.com",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1780655811/gigcvgm32vfm7uzbmr3q.png",
    description: "The gold standard for e-commerce email and SMS marketing automation.",
    category: "Automation",
    email: "partners@klaviyo.com",
    status: "approved",
    created_at: "2026-06-05T01:00:00Z",
    detailed_overview: JSON.stringify({
      overview: "Klaviyo is the ultimate marketing automation platform built specifically for e-commerce. It uses historical and real-time data to personalize email and SMS campaigns, significantly boosting customer lifetime value.",
      title1: "Hyper-Targeted Segmentation",
      desc1: "Target customers based on exact behaviors like specific items viewed, purchase frequency, and predictive lifetime value.",
      title2: "Unified Email & SMS",
      desc2: "Manage your email campaigns and text messaging from a single dashboard for perfectly timed multi-channel marketing."
    }),
    key_features: ["Predictive Analytics", "Pre-built Flow Templates", "Deep E-commerce Integrations"],
    key_features_descriptions: [
      "AI automatically predicts next purchase dates, churn risk, and customer lifetime value.",
      "Launch proven automated flows like abandoned cart and win-back campaigns in just minutes.",
      "Natively syncs with Shopify, WooCommerce, and BigCommerce to pull in all customer data instantly."
    ],
    rating: 4.9,
    rating_count: 3241,
    integration_guide_1_label: "Shopify Integration",
    integration_guide_1_url: "https://www.klaviyo.com/integrations/shopify",
    integration_guide_2_label: "Marketing Flows",
    integration_guide_2_url: "https://www.klaviyo.com/features/automation"
  },
  {
    id: "d39724d5-77b4-49e5-ada0-2719a151beca",
    title: "Rebuy",
    url: "https://www.rebuyengine.com",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1780655815/ctiyvodmcjr4yqnfavms.gif",
    description: "AI-powered personalization and merchandising engine for scaling Shopify brands.",
    category: "Store Optimization",
    email: "hello@rebuyengine.com",
    status: "approved",
    created_at: "2026-06-05T02:00:00Z",
    detailed_overview: JSON.stringify({
      overview: "Rebuy Engine increases Average Order Value (AOV) by seamlessly integrating AI-driven product recommendations throughout the entire customer journey, from the homepage to the post-purchase thank you page.",
      title1: "Smart Cart Upsells",
      desc1: "Turn your standard cart into a revenue engine with progress bars, free shipping thresholds, and targeted add-ons.",
      title2: "Post-Purchase Offers",
      desc2: "Present highly converting one-click upsell offers immediately after a customer completes checkout."
    }),
    key_features: ["AI Recommendation Engine", "Customizable Smart Cart", "One-Click Upsells"],
    key_features_descriptions: [
      "Machine learning models automatically suggest the most relevant products to each individual shopper.",
      "A fully customizable slide-out cart that replaces the default Shopify cart for better conversions.",
      "Maximize AOV by offering exclusive post-purchase deals that require zero friction to buy."
    ],
    rating: 4.8,
    rating_count: 856,
    integration_guide_1_label: "Smart Cart Setup",
    integration_guide_1_url: "https://www.rebuyengine.com/features/smart-cart",
    integration_guide_2_label: "Upsell Strategies",
    integration_guide_2_url: "https://www.rebuyengine.com/features/upsells"
  },
  {
    id: "1e5706f6-c04c-41d7-a9be-9a1f275e5d25",
    title: "Triple Whale",
    url: "https://www.triplewhale.com",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1780655826/xsh57hiji7owopgcakwa.gif",
    description: "The ultimate e-commerce operating system for tracking ROAS and attribution.",
    category: "Automation",
    email: "support@triplewhale.com",
    status: "approved",
    created_at: "2026-06-05T03:00:00Z",
    detailed_overview: JSON.stringify({
      overview: "Triple Whale centralizes all your e-commerce metrics into one beautiful dashboard. By bypassing iOS tracking limitations with first-party data, it gives founders the exact truth about which ads are actually driving profit.",
      title1: "True Attribution",
      desc1: "Stop guessing. Triple Pixel tracking accurately maps the entire customer journey from the first ad click to the final purchase.",
      title2: "Profit Tracking",
      desc2: "Automatically calculates your Net Profit by syncing COGS, shipping costs, and daily ad spend across all platforms."
    }),
    key_features: ["Triple Pixel Attribution", "Creative Cockpit", "Real-Time Profitability"],
    key_features_descriptions: [
      "Proprietary first-party tracking pixel that accurately attributes sales despite privacy updates.",
      "Visually analyze the ROI of every single image and video ad creative across Meta and TikTok.",
      "A live view of your Net Margin, Contribution Margin, and blended ROAS in one central hub."
    ],
    rating: 5.0,
    rating_count: 1420,
    integration_guide_1_label: "Attribution Setup",
    integration_guide_1_url: "https://www.triplewhale.com/features/attribution",
    integration_guide_2_label: "Profit Dashboard",
    integration_guide_2_url: "https://www.triplewhale.com/features/profit-tracking"
  },
  {
    id: "87eb5f48-e09d-4072-837d-5a8c9afc9586",
    title: "Synthesia",
    url: "https://www.synthesia.io",
    image_url: "https://res.cloudinary.com/ditb2aeea/image/upload/v1780655828/ah1qufejn5idxy2jnlpq.png",
    description: "Create professional AI video content for product tutorials and ads without a camera.",
    category: "Visual & Design",
    email: "support@synthesia.io",
    status: "approved",
    created_at: "2026-06-05T04:00:00Z",
    detailed_overview: JSON.stringify({
      overview: "Synthesia transforms text into engaging video content using hyper-realistic AI avatars. It is perfect for e-commerce brands looking to scale their video ads, product explainers, and customer onboarding tutorials without expensive studio shoots.",
      title1: "Lifelike AI Avatars",
      desc1: "Choose from over 140 diverse AI avatars to present your products naturally and professionally.",
      title2: "Multilingual Scaling",
      desc2: "Translate your video scripts into 120+ languages instantly to launch global marketing campaigns."
    }),
    key_features: ["Text-to-Video Engine", "Custom AI Avatars", "Auto-Translation"],
    key_features_descriptions: [
      "Type your script and generate a high-quality video with a human presenter in minutes.",
      "Create a custom avatar of your brand's founder or spokesperson for consistent marketing.",
      "Reach international markets effortlessly with automatic lip-syncing in over 120 languages."
    ],
    rating: 4.7,
    rating_count: 2105,
    integration_guide_1_label: "Video Ad Templates",
    integration_guide_1_url: "https://www.synthesia.io/templates",
    integration_guide_2_label: "Custom Avatars",
    integration_guide_2_url: "https://www.synthesia.io/features/custom-avatars"
  }
];