export interface SeedItem {
  id: string;
  title: string;
  url: string;
  description: string;
  image_url: string;
  category: string;
  email: string;
  status: string;
  created_at: string;
  detailed_overview?: string;
  key_features?: string[];
  customer_review?: string;
  customer_review_author?: string;
  integration_guide_1_label?: string;
  integration_guide_2_label?: string;
}

export const SEED_ITEMS: SeedItem[] = [
  // ==================== 1. Visual & Design (5 items) ====================
  {
    id: "seed-pebblely",
    title: "Pebblely",
    url: "https://pebblely.com",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://pebblely.com",
    description: "Beautiful AI product photography in seconds. Turn any boring product photo into a professional studio shot.",
    category: "Visual & Design",
    email: "creator@pebblely.com",
    status: "approved",
    created_at: "2026-05-23T12:00:00Z",
    detailed_overview: "Pebblely utilizes generative AI to transform basic product images into stunning marketing assets. By automatically removing backgrounds and generating realistic studio scenes, it eliminates the need for expensive photoshoots, saving solo creators hours of tedious manual editing.",
    key_features: ["AI Scene Generation", "Instant Background Removal", "Multi-Asset Batch Export"],
    customer_review: "Saved us over 40 hours of manual editing last month alone. Absolute game-changer for solo sellers!",
    customer_review_author: "Sarah J. - Shopify Plus Merchant",
    integration_guide_1_label: "Pebblely Shopify App Setup Guide",
    integration_guide_2_label: "API Endpoint Documentation"
  },
  {
    id: "seed-flair-ai",
    title: "Flair AI",
    url: "https://flair.ai",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://flair.ai",
    description: "The AI design tool for branded content. Generate high-end product assets and campaigns instantly.",
    category: "Visual & Design",
    email: "creator@flair.ai",
    status: "approved",
    created_at: "2026-05-23T11:50:00Z",
    detailed_overview: "Flair AI is a drag-and-drop design tool engineered specifically for consumer brands. It allows users to place their products in high-conversion digital environments, complete with smart lighting and contextual props that reflect premium brand aesthetics.",
    key_features: ["Smart Lighting Placement", "Drag-and-Drop Props", "High-Res Content Upscaling"],
    customer_review: "The absolute fastest way to create high-end product ads without a professional studio crew.",
    customer_review_author: "David K. - Brand Director",
    integration_guide_1_label: "Flair AI Asset Pipeline Integration",
    integration_guide_2_label: "Canva Export Workflow"
  },
  {
    id: "seed-pixelcut",
    title: "Pixelcut",
    url: "https://www.pixelcut.ai",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://www.pixelcut.ai",
    description: "Fast and clean background removal and product photo editing tailored for online commerce.",
    category: "Visual & Design",
    email: "creator@pixelcut.ai",
    status: "approved",
    created_at: "2026-05-23T11:40:00Z",
    detailed_overview: "Pixelcut focuses on lightning-fast mobile and web editing for active e-commerce merchants. Its optimized AI model handles bulk background cutouts instantly, making it the perfect tool for multi-channel sellers listing hundreds of items daily.",
    key_features: ["Bulk Object Eraser", "Shadow Control Customization", "E-commerce Template Library"],
    customer_review: "Listing new items on Etsy used to take all day. Now with Pixelcut, it's done in minutes.",
    customer_review_author: "Emma L. - Boutique Owner",
    integration_guide_1_label: "Pixelcut Web Editor Extension Guide",
    integration_guide_2_label: "Etsy Marketplace Sync API"
  },
  {
    id: "seed-claid-ai",
    title: "Claid.ai",
    url: "https://claid.ai",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://claid.ai",
    description: "AI-powered image upscaler and editor built to enhance user-generated marketplace photos.",
    category: "Visual & Design",
    email: "creator@claid.ai",
    status: "approved",
    created_at: "2026-05-23T11:30:00Z",
    detailed_overview: "Claid.ai specializes in fixing poor quality product photos automatically. It uses sophisticated neural networks to sharpen blurry textures, fix complex lighting issues, and standardize pixel dimensions for strict multi-vendor marketplaces.",
    key_features: ["Automated Image Enhancement", "Marketplace Photo Standardizer", "Smart Light Correction"],
    customer_review: "Drastically improved our catalog quality. Conversions went up after cleaning up supplier images.",
    customer_review_author: "Marcus T. - Dropshipping Manager",
    integration_guide_1_label: "Claid API Integration Endpoints",
    integration_guide_2_label: "Shopify Webhook Sync"
  },
  {
    id: "seed-photoroom",
    title: "Photoroom",
    url: "https://www.photoroom.com",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://www.photoroom.com",
    description: "The all-in-one creative photo editing platform that helps small business owners create pro product images.",
    category: "Visual & Design",
    email: "creator@photoroom.com",
    status: "approved",
    created_at: "2026-05-23T11:20:00Z",
    detailed_overview: "Photoroom is a powerhouse for mobile commerce sellers. It enables swift, pro-level retouching directly from a smartphone or browser, allowing sellers to clean up product listings, add stylized text, and format pictures for marketplaces seamlessly.",
    key_features: ["Pro Retouching Suite", "Batch Processing Engine", "Dynamic Text Overlay AI"],
    customer_review: "Our team uses this every single day. The mobile app parity with web is incredible.",
    customer_review_author: "Jessica H. - Content Lead",
    integration_guide_1_label: "Photoroom Mobile to Web Asset Sync",
    integration_guide_2_label: "Bulk CSV Image Importer"
  },

  // ==================== 2. Copywriting & Marketing (5 items) ====================
  {
    id: "seed-predis-ai",
    title: "Predis.ai",
    url: "https://predis.ai",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://predis.ai",
    description: "AI social media post generator. Create video reels, carousels, and captions just from a text prompt.",
    category: "Copywriting & Marketing",
    email: "creator@predis.ai",
    status: "approved",
    created_at: "2026-05-23T11:10:00Z",
    detailed_overview: "Predis.ai bridge the gap between product catalogs and social media. By simply inputting a product URL or text description, the AI spits out fully edited Instagram reels, interactive carousels, and engaging captions optimized for store traffic.",
    key_features: ["AI Video Reels Generator", "Competitor Analysis Dashboard", "Direct Meta Scheduling"],
    customer_review: "Managing social accounts for three brands became manageable thanks to Predis.",
    customer_review_author: "Alex B. - Multi-Store Owner",
    integration_guide_1_label: "Predis Shopify Catalog Connection Guide",
    integration_guide_2_label: "Meta Business Suite Sync"
  },
  {
    id: "seed-jasper",
    title: "Jasper",
    url: "https://www.jasper.ai",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://www.jasper.ai",
    description: "Enterprise AI copywriter optimized to write high-converting Shopify product descriptions and ads.",
    category: "Copywriting & Marketing",
    email: "creator@jasper.ai",
    status: "approved",
    created_at: "2026-05-23T11:00:00Z",
    detailed_overview: "Jasper is an advanced writing assistant trained extensively on conversion psychology. It helps merchants brainstorm catchy hooks, craft SEO-friendly product pages, and generate high-performing ad variants tailored to target audience segments.",
    key_features: ["Brand Voice Personalization", "SEO Keywords Injector", "A/B Test Ad Variant Writer"],
    customer_review: "Our ad copy CTR increased by 25% since we let Jasper write our product taglines.",
    customer_review_author: "Ryan M. - Growth Marketer",
    integration_guide_1_label: "Jasper Chrome Extension Workflow",
    integration_guide_2_label: "Shopify Product Admin Sync"
  },
  {
    id: "seed-copy-ai",
    title: "Copy.ai",
    url: "https://www.copy.ai",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://www.copy.ai",
    description: "AI marketing OS designed to automate bulk e-commerce email marketing campaigns and ad copies.",
    category: "Copywriting & Marketing",
    email: "creator@copy.ai",
    status: "approved",
    created_at: "2026-05-23T10:50:00Z",
    detailed_overview: "Copy.ai focuses on large-scale marketing workflows. Instead of writing individual newsletters, its e-commerce automation operating system allows sellers to instantly generate entire email sequencing flows based on consumer behavior triggers.",
    key_features: ["Marketing Workflow Automation", "Bulk Email Copy Sequencer", "Multi-Language Ad Translator"],
    customer_review: "Automating our abandoned cart email sequences took less than 10 minutes with Copy.ai.",
    customer_review_author: "Liam F. - Operations Lead",
    integration_guide_1_label: "Klaviyo Integration Walkthrough",
    integration_guide_2_label: "Copy.ai Webhook Configurations"
  },
  {
    id: "seed-adcreative-ai",
    title: "AdCreative.ai",
    url: "https://www.adcreative.ai",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://www.adcreative.ai",
    description: "Generate conversion-focused ad creatives and banners within seconds using a highly trained prediction AI.",
    category: "Copywriting & Marketing",
    email: "creator@adcreative.ai",
    status: "approved",
    created_at: "2026-05-23T10:40:00Z",
    detailed_overview: "AdCreative.ai is a data-backed creative engine. It analyzes millions of successful advertising banners across the web to automatically generate layouts that drive users to click, minimizing ad spend fatigue.",
    key_features: ["Conversion Rate Prediction AI", "Bulk Banner Ad Resizer", "Brand Kit Auto-Integration"],
    customer_review: "Takes the guesswork out of creative testing. The AI-recommended layouts just perform better.",
    customer_review_author: "Chloe W. - Paid Media Specialist",
    integration_guide_1_label: "Google & Meta Ad Account Direct Sync",
    integration_guide_2_label: "API Creative Upload"
  },
  {
    id: "seed-glossai",
    title: "GlossAi",
    url: "https://gloss.ai",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://gloss.ai",
    description: "Turn long-form customer review videos or podcasts into bite-sized, viral social media shorts for your brand.",
    category: "Copywriting & Marketing",
    email: "creator@gloss.ai",
    status: "approved",
    created_at: "2026-05-23T10:30:00Z",
    detailed_overview: "GlossAi repurposes video content to unlock social proof potential. It scans long unboxing videos, customer reviews, or brand podcasts to isolate the most exciting segments, auto-generating short-form video clips complete with stylish subtitles.",
    key_features: ["AI Video Summarization", "Auto-Subtitling Engine", "Social Media Trend Matcher"],
    customer_review: "We generated a month's worth of TikTok shorts from just one single YouTube review.",
    customer_review_author: "Tyler V. - Video Producer",
    integration_guide_1_label: "YouTube Content Importer Endpoints",
    integration_guide_2_label: "GlossAi Workspace Sharing Guide"
  },

  // ==================== 3. Store Optimization (5 items) ====================
  {
    id: "seed-omnisearch-ai",
    title: "OmniSearch",
    url: "https://omnisearch.ai",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://omnisearch.ai",
    description: "Lightning-fast semantic search for large-scale e-commerce product catalogs.",
    category: "Store Optimization",
    email: "creator@omnisearch.ai",
    status: "approved",
    created_at: "2026-05-23T10:20:00Z",
    detailed_overview: "OmniSearch represents a next-generation utility tailored specifically for e-commerce operators and solo brands. By automating complex visual adjustments and search logic, this tool removes technical barriers and allows founders to focus entirely on high-level growth strategies.",
    key_features: ["Visual Excellence", "Conversion Lift", "Simple Launch"],
    customer_review: "Unlocked search visibility for our complex 5,000 SKU clothing store catalog overnight.",
    customer_review_author: "Sarah J. - Shopify Plus Merchant",
    integration_guide_1_label: "OmniSearch Setup Guide for E-commerce",
    integration_guide_2_label: "SaaS Integration Endpoints"
  },
  {
    id: "seed-instant",
    title: "Instant",
    url: "https://www.instant.so",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://www.instant.so",
    description: "The fastest Shopify landing page builder with pre-made, high-converting drag-and-drop elements.",
    category: "Store Optimization",
    email: "creator@instant.so",
    status: "approved",
    created_at: "2026-05-23T10:10:00Z",
    detailed_overview: "Instant lets brand owners launch optimized promotional landing pages without touching code. Its server-side rendering architecture ensures pages load instantly, minimizing bounce rates and maximizing dynamic checkout conversions.",
    key_features: ["No-Code Page Structurer", "Ultra-Fast Page Load Speed", "Shopify Section Exporter"],
    customer_review: "The load speeds on our landing pages dropped below 0.5s. Our conversion rates spiked.",
    customer_review_author: "Nate D. - Direct-to-Consumer Founder",
    integration_guide_1_label: "Instant.so Theme Integration Guide",
    integration_guide_2_label: "Custom Domain Setup CSS"
  },
  {
    id: "seed-alia-popups",
    title: "Alia Popups",
    url: "https://www.aliapopups.com",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://www.aliapopups.com",
    description: "Smart behavioral popups that prevent shopping cart abandonment with dynamic, real-time incentives.",
    category: "Store Optimization",
    email: "creator@aliapopups.com",
    status: "approved",
    created_at: "2026-05-23T10:00:00Z",
    detailed_overview: "Alia Popups uses smart exit-intent tracking to rescue lost revenue. The platform accurately senses when a customer is about to leave your storefront and deploys targeted, personalized offers to secure the checkout session.",
    key_features: ["Exit-Intent Smart Detection", "Dynamic Coupon Code Generator", "A/B Split Testing Panel"],
    customer_review: "Recovered over $5,000 in sales during our first week of launching Alia.",
    customer_review_author: "Sophia R. - E-commerce Director",
    integration_guide_1_label: "Alia JavaScript Snippet Installation",
    integration_guide_2_label: "Shopify Checkout API Sync"
  },
  {
    id: "seed-octane-ai",
    title: "Octane AI",
    url: "https://www.octaneai.com",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://www.octaneai.com",
    description: "Create engaging product recommendation quizzes to boost store sales and collect zero-party customer data.",
    category: "Store Optimization",
    email: "creator@octaneai.com",
    status: "approved",
    created_at: "2026-05-23T09:50:00Z",
    detailed_overview: "Octane AI enables personalized shopping journeys through guided quizzes. By questioning buyers about their exact preferences, it creates customized product recommendation sets that build trust and lift average order values.",
    key_features: ["Interactive Quiz Builder", "Zero-Party Data Collector", "Personalized Recommendation Engine"],
    customer_review: "Our quiz is our highest-converting page. Customers love the tailored skincare advice.",
    customer_review_author: "Hannah P. - Wellness Brand Founder",
    integration_guide_1_label: "Octane AI Quiz Embed Instructions",
    integration_guide_2_label: "Klaviyo Customer Profile Mapping"
  },
  {
    id: "seed-loox",
    title: "Loox",
    url: "https://loox.app",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://loox.app",
    description: "Beautiful photo and video product reviews app designed to build high trust and social proof.",
    category: "Store Optimization",
    email: "creator@loox.app",
    status: "approved",
    created_at: "2026-05-23T09:40:00Z",
    detailed_overview: "Loox automates the process of gathering customer validation. It sends beautiful, timed follow-up review request emails, encouraging buyers to upload photo and video proof in exchange for discounts, building premium social proof cards.",
    key_features: ["Automated Review Requester", "Photo/Video Gallery Widgets", "Review Incentives Manager"],
    customer_review: "Visual reviews are crucial for conversion. Loox makes collecting them entirely frictionless.",
    customer_review_author: "Ben S. - Gadget Store Owner",
    integration_guide_1_label: "Loox Review Widget Injection Guide",
    integration_guide_2_label: "Google Shopping Review Feed Sync"
  },

  // ==================== 4. Automation (5 items) ====================
  {
    id: "seed-tidio-lyro",
    title: "Tidio Lyro",
    url: "https://www.tidio.com/lyro-ai/",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://www.tidio.com/lyro-ai/",
    description: "Conversational AI customer service chatbot that resolves up to 70% of customer inquiries on autopilot.",
    category: "Automation",
    email: "creator@tidio.com",
    status: "approved",
    created_at: "2026-05-23T09:30:00Z",
    detailed_overview: "Tidio Lyro handles customer care heavy lifting. Using state-of-the-art LLMs, it securely reads your store's FAQ data and answers order tracking or refund policy questions in seconds, reducing customer support queue times.",
    key_features: ["LLM-Powered Support Chatbot", "Order Tracking Live Sync", "Human Agent Handover Logic"],
    customer_review: "Lyro handles all our late-night support tickets perfectly without human intervention.",
    customer_review_author: "Oliver G. - Customer Success Lead",
    integration_guide_1_label: "Tidio Lyro AI Training Integration",
    integration_guide_2_label: "Shopify Admin API Handshake"
  },
  {
    id: "seed-thoughtmetric",
    title: "ThoughtMetric",
    url: "https://thoughtmetric.io",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://thoughtmetric.io",
    description: "E-commerce marketing attribution dashboard that tracks ROAS across TikTok, Meta, and Google Ads.",
    category: "Automation",
    email: "creator@thoughtmetric.io",
    status: "approved",
    created_at: "2026-05-23T09:20:00Z",
    detailed_overview: "ThoughtMetric solves pixel tracking inaccuracies caused by privacy updates. It utilizes advanced AI cookie-less tracking to trace the exact customer journey, assigning marketing attribution values to the channels that actually generated the sale.",
    key_features: ["Cookie-less Tracking Pixel", "Multi-Touch Attribution Model", "Cross-Channel Ad ROAS Dashboard"],
    customer_review: "Finally, our Facebook and Shopify dashboard numbers match up. Lifesaver for ad tracking.",
    customer_review_author: "Kevin Z. - Digital Ads Manager",
    integration_guide_1_label: "ThoughtMetric Pixel Setup Walkthrough",
    integration_guide_2_label: "Google Analytics 4 Connection API"
  },
  {
    id: "seed-alloy-automation",
    title: "Alloy Automation",
    url: "https://runalloy.com",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://runalloy.com",
    description: "No-code automation engine connecting your Shopify store, fulfillment warehouse, and marketing tools.",
    category: "Automation",
    email: "creator@runalloy.com",
    status: "approved",
    created_at: "2026-05-23T09:10:00Z",
    detailed_overview: "Alloy Automation functions as the central central nervous system for complex store workflows. It enables non-technical operators to build logic chains, such as automatically tag high-value customers or trigger warehouse shipping updates.",
    key_features: ["Visual Workflow Builder", "100+ Pre-built SaaS Triggers", "Advanced Logic & Tag Filter"],
    customer_review: "Alloy automated our custom fraud prevention and loyalty program tagging completely.",
    customer_review_author: "Rachel E. - COO",
    integration_guide_1_label: "Alloy App Store Connection Manual",
    integration_guide_2_label: "Webhook Payload Parser Guide"
  },
  {
    id: "seed-gorgias",
    title: "Gorgias",
    url: "https://www.gorgias.com",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://www.gorgias.com",
    description: "A specialized helpdesk for e-commerce merchants that centralizes customer support messages.",
    category: "Automation",
    email: "creator@gorgias.com",
    status: "approved",
    created_at: "2026-05-23T09:00:00Z",
    detailed_overview: "Gorgias pulls all communication channels into a single timeline. Whether a buyer messages via Instagram DM, email, or live chat, support teams can edit Shopify orders directly inside the ticket window without switching screens.",
    key_features: ["Multi-Channel Unified Inbox", "Direct Shopify Order Editor", "Macro Response Automation"],
    customer_review: "Our first-response time dropped to under 5 minutes because everything is in one screen.",
    customer_review_author: "Daniel S. - Support Manager",
    integration_guide_1_label: "Gorgias Helpdesk Omni-Channel Sync",
    integration_guide_2_label: "Shopify App Store Installation"
  },
  {
    id: "seed-matrixify",
    title: "Matrixify",
    url: "https://matrixify.app",
    image_url: "https://image.thum.io/get/width/1200/crop/675/https://matrixify.app",
    description: "Bulk data manager for Shopify. Easily import, export, and update thousands of products and orders.",
    category: "Automation",
    email: "creator@matrixify.app",
    status: "approved",
    created_at: "2026-05-23T08:50:00Z",
    detailed_overview: "Matrixify excels at heavy database data lifting. It allows store managers to export thousands of items into Excel or Google Sheets, perform mass price or inventory adjustments, and safely import everything back into Shopify with absolute data integrity.",
    key_features: ["Bulk Product Data Manager", "Metafield Excel Batch Editor", "Automated Backup Scheduler"],
    customer_review: "Migrating 20,000 product variants from WooCommerce to Shopify took one click with Matrixify.",
    customer_review_author: "Andrew J. - E-commerce Consultant",
    integration_guide_1_label: "Matrixify Batch CSV Format Manual",
    integration_guide_2_label: "FTP/SFTP Scheduled Auto-Export"
  }
];
